apiVersion: v2
name: buntime
description: A Helm chart for Buntime - Worker Pool Runtime for Bun applications
type: application
version: 0.5.1
appVersion: "1.4.0"
icon: https://bun.sh/logo.svg
keywords:
  - buntime
  - bun
  - runtime
  - worker-pool
  - microservices
home: https://github.com/djalmajr/buntime
sources:
  - https://github.com/djalmajr/buntime
maintainers:
  - name: Djalma Júnior
    email: noreply@djalmajr.dev
